<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PrinterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get(
    '/',
    [HomeController::class, 'index']
)->name('home');

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get(
    '/create-printer',
    [PrinterController::class, 'create']
)->middleware(['auth', 'verified'])->name('createPrinter');

Route::post(
    '/store-printer',
    [PrinterController::class, 'store']
)->middleware(['auth', 'verified'])->name('storePrinter');

Route::get(
    '/get-printers-info',
    [PrinterController::class, 'getPrintersInfo']
);

Route::get(
    '/contact-owner/{userId}',
    [HomeController::class, 'contactOwner']
)->middleware(['auth', 'verified'])->name('contactOwner');

Route::post(
    '/contact-owner/handle-form',
    [HomeController::class, 'handleForm']
)->middleware(['auth', 'verified'])->name('handleForm');


// GENERATED BY BREEZE
Route::get('/dashboard', function () {
    return view('dashboard')->with('user', Auth::user());
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__ . '/auth.php';
